RabbitMQ:
  host: localhost
  queues:
    amazon_queue: amazon
    walmart_queue: walmart
    db_writer_queue: db_write
    db_reader_queue: db_read

MongoDB:
  host: localhost
  db: products
  collections:
    amazon.com: amazon
    walmart.com: walmart

Amazon:
  api: https://ebazon-prod.herokuapp.com/ybl_assignment/amazon/
  keys:
    - - _id
    - - source
    - - title
    - - price

Walmart:
  api: https://developer.api.walmart.com/api-proxy/service/affil/product/v2/items/
  headers_api: https://ebazon-prod.herokuapp.com/ybl_assignment/walmart/headers
  headers_json: ./walmart_headers.json
  keys:
    - - itemId
      - _id
    - - name
      - title
    - - salePrice
      - price
    - - sellerInfo
      - source