rabbitmq:
  host: rabbitmq
  queues:
    amazon_queue: amazon
    walmart_queue: walmart
    db_writer_queue: db_write
    db_reader_queue: db_read_by_id
    db_filter_queue: db_read_by_filter
  exchanges:
    fetcher_writer_exchange: response

mongodb:
  host: mongodb
  db: products
  collections:
    amazon.com: amazon
    walmart.com: walmart

amazon:
  api: https://ebazon-prod.herokuapp.com/ybl_assignment/amazon/
  depends_on:
    - - rabbitmq
      - 5672
  keys:
    - - _id
    - - source
    - - title
    - - price

walmart:
  api: https://developer.api.walmart.com/api-proxy/service/affil/product/v2/items/
  headers_api: https://ebazon-prod.herokuapp.com/ybl_assignment/walmart/headers
  headers_json: ./walmart_headers.json
  depends_on:
    - - rabbitmq
      - 5672
  keys:
    - - itemId
      - _id
    - - name
      - title
    - - salePrice
      - price
    - - sellerInfo
      - source

db_reader:
  depends_on:
    - - rabbitmq
      - 5672
    - - mongodb
      - 27017

db_filter:
  depends_on:
    - - rabbitmq
      - 5672
    - - mongodb
      - 27017

db_writer:
  depends_on:
    - - rabbitmq
      - 5672
    - - mongodb
      - 27017

web_server:
  db_read:
  depends_on:
    - - rabbitmq
      - 5672
