version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - yaballe_API
    deploy:
      replicas: 1
    ports:
      - 15672:15672
    container_name: rabbitmq

  mongodb:
    image: mongo
    deploy:
      replicas: 1
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - yaballe_API
    volumes:
      - mongodata:/data/db
    command: --quiet
    
  amazon_fetcher:
    image: orireiter/walmart_amazon_api:amazon_fetcher_0.0.8
    deploy:
      replicas: 1
    networks:
      - yaballe_API
    volumes:
      - ./config.yml:/app/config.yml

  walmart_fetcher:
    image: orireiter/walmart_amazon_api:walmart_fetcher_0.0.8
    deploy:
      replicas: 1
    networks:
      - yaballe_API
    volumes:
      - ./config.yml:/app/config.yml
      - ./walmart_headers.json:/app/walmart_headers.json

  walmart_header_fetcher:
    image: orireiter/walmart_amazon_api:walmart_header_fetcher_0.0.8
    deploy:
      replicas: 1
    networks:
      - yaballe_API
    volumes:
      - ./config.yml:/app/config.yml
      - ./walmart_headers.json:/app/walmart_headers.json

  web_server:
    image: orireiter/walmart_amazon_api:web_server_0.0.8
    deploy:
      replicas: 1
    networks:
      - yaballe_API
    volumes:
      - ./config.yml:/app/config.yml
      - ./config.json:/docker-entrypoint.d/config.json
    ports:
      - 80:80

  db_reader_by_id:
    image: orireiter/walmart_amazon_api:db_reader_by_id_0.0.8
    deploy:
      replicas: 4
    networks:
      - yaballe_API
    volumes:
      - ./config.yml:/app/config.yml

  db_reader_by_filter:
    image: orireiter/walmart_amazon_api:db_reader_by_filter_0.0.8
    deploy:
      replicas: 1
    networks:
      - yaballe_API
    volumes:
      - ./config.yml:/app/config.yml

  db_writer:
    image: orireiter/walmart_amazon_api:db_writer_0.0.8
    deploy:
      replicas: 1
    networks:
      - yaballe_API
    volumes:
      - ./config.yml:/app/config.yml

networks:
  yaballe_API:
    driver: bridge

volumes:
  mongodata: